#!/bin/sh
# wrapper for yt-dlp

MUSICDIR="${XDG_MUSIC_DIR:-$HOME/music}"
VIDEODIR="${XDG_VIDEOS_DIR:-$HOME/Videos}"

case $1 in
v)
	mkdir -p "$VIDEODIR"
	herbe "Video download started"
	yt-dlp -f 'bv,ba' -o '%(title)s [%(id)s].%(ext)s'\
	-P "$VIDEODIR" "$2" &&
	herbe "Video downloaded" ||
		(herbe "Error: No internet connection" && exit 1) ;;
m)
	mkdir -p "$MUSICDIR/download"
	herbe "Music download started"
	yt-dlp -f 'ba' -x --embed-thumbnail --audio-format mp3\
	-o '%(title)s [%(id)s].%(ext)s' -P "$MUSICDIR/download" "$2" &&
	herbe "Music downloaded" ||
		(herbe "Error: No internet connection" && exit 1) ;;
p)
	NAME=$(printf '' | dmenu -p 'Name ')
	mkdir -p "$MUSICDIR/$NAME"
	herbe "Playlist download started"
	yt-dlp -f 'ba' -x --embed-thumbnail --audio-format mp3\
	-o '%(playlist_index)s - %(title)s [%(id)s].%(ext)s'\
	-P "$MUSICDIR/$NAME" "$2" &&
	herbe "Playlist downloaded" ||
		(herbe "Error: No internet connection" && exit 1) ;;
*)
	exit 1 ;;
esac
